### ISSUE TITLE
a suggestion

### ISSUE THREAD

**Issue by ake020675** [daviddoria/PointCloudHoleFilling#1]
I think this repo is a implementation of this paper:
Doria D, Radke R J.: Filling large holes in lidar data by
inpainting depth gradients[C]. 2012 IEEE Computer Soci-
ety Conference on Computer Vision and Pattern Recogni-
tion Workshops. IEEE, pp. 65-72.(2012).

Maybe it's better to add a readme file?

**Comment by daviddoria** [comment]
That's more or less correct :). There's likely been some tinkering with parameters since the paper was published, but the spirit of the algorithm should be there! Always happy to accept pull requests if you want to add a readme or improve the code in another way!
